// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Windows_Phone_System_H
#define WINRT_Windows_Phone_System_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/impl/Windows.Phone.System.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Phone_System_ISystemProtectionStatics<D>::ScreenLocked() const
    {
        bool value{};
        consume_general<winrt::Windows::Phone::System::ISystemProtectionStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::System::ISystemProtectionStatics>::get_ScreenLocked, &value);
        return value;
    }
    template <typename D> auto consume_Windows_Phone_System_ISystemProtectionUnlockStatics<D>::RequestScreenUnlock() const
    {
        consume_general<winrt::Windows::Phone::System::ISystemProtectionUnlockStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::System::ISystemProtectionUnlockStatics>::RequestScreenUnlock);
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Phone::System::ISystemProtectionStatics> : produce_base<D, winrt::Windows::Phone::System::ISystemProtectionStatics>
    {
        std::int32_t __stdcall get_ScreenLocked(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().ScreenLocked());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Phone::System::ISystemProtectionUnlockStatics> : produce_base<D, winrt::Windows::Phone::System::ISystemProtectionUnlockStatics>
    {
        std::int32_t __stdcall RequestScreenUnlock() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().RequestScreenUnlock();
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Phone::System
{
    inline auto SystemProtection::ScreenLocked()
    {
        return impl::call_factory_cast<bool(*)(ISystemProtectionStatics const&), SystemProtection, ISystemProtectionStatics>([](ISystemProtectionStatics const& f) { return f.ScreenLocked(); });
    }
    inline auto SystemProtection::RequestScreenUnlock()
    {
        impl::call_factory_cast<void(*)(ISystemProtectionUnlockStatics const&), SystemProtection, ISystemProtectionUnlockStatics>([](ISystemProtectionUnlockStatics const& f) { return f.RequestScreenUnlock(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Phone::System::ISystemProtectionStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Phone::System::ISystemProtectionUnlockStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Phone::System::SystemProtection> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
