// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Windows_Phone_Media_Devices_H
#define WINRT_Windows_Phone_Media_Devices_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Phone.Media.Devices.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::GetAudioEndpoint() const
    {
        winrt::Windows::Phone::Media::Devices::AudioRoutingEndpoint endpoint{};
        consume_general<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>::GetAudioEndpoint, reinterpret_cast<std::int32_t*>(&endpoint));
        return endpoint;
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::SetAudioEndpoint(winrt::Windows::Phone::Media::Devices::AudioRoutingEndpoint const& endpoint) const
    {
        consume_general<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>::SetAudioEndpoint, static_cast<std::int32_t>(endpoint));
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::AudioEndpointChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Phone::Media::Devices::AudioRoutingManager, winrt::Windows::Foundation::IInspectable> const& endpointChangeHandler) const
    {
        winrt::event_token token{};
        consume_general<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>::add_AudioEndpointChanged, *(void**)(&endpointChangeHandler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::AudioEndpointChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Phone::Media::Devices::AudioRoutingManager, winrt::Windows::Foundation::IInspectable> const& endpointChangeHandler) const
    {
        return impl::make_event_revoker<D, AudioEndpointChanged_revoker>(this, AudioEndpointChanged(endpointChangeHandler));
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::AudioEndpointChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>::remove_AudioEndpointChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManager<D>::AvailableAudioEndpoints() const
    {
        winrt::Windows::Phone::Media::Devices::AvailableAudioRoutingEndpoints value{};
        consume_general<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>::get_AvailableAudioEndpoints, reinterpret_cast<std::uint32_t*>(&value));
        return value;
    }
    template <typename D> auto consume_Windows_Phone_Media_Devices_IAudioRoutingManagerStatics<D>::GetDefault() const
    {
        void* audioRoutingManager{};
        consume_general<winrt::Windows::Phone::Media::Devices::IAudioRoutingManagerStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::Phone::Media::Devices::IAudioRoutingManagerStatics>::GetDefault, &audioRoutingManager);
        return winrt::Windows::Phone::Media::Devices::AudioRoutingManager{ audioRoutingManager, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Phone::Media::Devices::IAudioRoutingManager> : produce_base<D, winrt::Windows::Phone::Media::Devices::IAudioRoutingManager>
    {
        std::int32_t __stdcall GetAudioEndpoint(std::int32_t* endpoint) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *endpoint = detach_from<winrt::Windows::Phone::Media::Devices::AudioRoutingEndpoint>(this->shim().GetAudioEndpoint());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall SetAudioEndpoint(std::int32_t endpoint) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().SetAudioEndpoint(*reinterpret_cast<winrt::Windows::Phone::Media::Devices::AudioRoutingEndpoint const*>(&endpoint));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_AudioEndpointChanged(void* endpointChangeHandler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().AudioEndpointChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Phone::Media::Devices::AudioRoutingManager, winrt::Windows::Foundation::IInspectable> const*>(&endpointChangeHandler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_AudioEndpointChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().AudioEndpointChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall get_AvailableAudioEndpoints(std::uint32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::Phone::Media::Devices::AvailableAudioRoutingEndpoints>(this->shim().AvailableAudioEndpoints());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::Phone::Media::Devices::IAudioRoutingManagerStatics> : produce_base<D, winrt::Windows::Phone::Media::Devices::IAudioRoutingManagerStatics>
    {
        std::int32_t __stdcall GetDefault(void** audioRoutingManager) noexcept final try
        {
            clear_abi(audioRoutingManager);
            typename D::abi_guard guard(this->shim());
            *audioRoutingManager = detach_from<winrt::Windows::Phone::Media::Devices::AudioRoutingManager>(this->shim().GetDefault());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::Phone::Media::Devices
{
    constexpr auto operator|(AvailableAudioRoutingEndpoints const left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        return static_cast<AvailableAudioRoutingEndpoints>(impl::to_underlying_type(left) | impl::to_underlying_type(right));
    }
    constexpr auto operator|=(AvailableAudioRoutingEndpoints& left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        left = left | right;
        return left;
    }
    constexpr auto operator&(AvailableAudioRoutingEndpoints const left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        return static_cast<AvailableAudioRoutingEndpoints>(impl::to_underlying_type(left) & impl::to_underlying_type(right));
    }
    constexpr auto operator&=(AvailableAudioRoutingEndpoints& left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        left = left & right;
        return left;
    }
    constexpr auto operator~(AvailableAudioRoutingEndpoints const value) noexcept
    {
        return static_cast<AvailableAudioRoutingEndpoints>(~impl::to_underlying_type(value));
    }
    constexpr auto operator^(AvailableAudioRoutingEndpoints const left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        return static_cast<AvailableAudioRoutingEndpoints>(impl::to_underlying_type(left) ^ impl::to_underlying_type(right));
    }
    constexpr auto operator^=(AvailableAudioRoutingEndpoints& left, AvailableAudioRoutingEndpoints const right) noexcept
    {
        left = left ^ right;
        return left;
    }
    inline auto AudioRoutingManager::GetDefault()
    {
        return impl::call_factory_cast<winrt::Windows::Phone::Media::Devices::AudioRoutingManager(*)(IAudioRoutingManagerStatics const&), AudioRoutingManager, IAudioRoutingManagerStatics>([](IAudioRoutingManagerStatics const& f) { return f.GetDefault(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::Phone::Media::Devices::IAudioRoutingManager> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Phone::Media::Devices::IAudioRoutingManagerStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::Phone::Media::Devices::AudioRoutingManager> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
