services:
  builder:
    build:
      context: .
      dockerfile: agent/builder/Dockerfile.builder
    image: rtsp-builder
    container_name: rtsp-builder
    profiles:
      - tools
    volumes:
      - .:/app
    restart: "no"
