// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Windows_Phone_Speech_Recognition_1_H
#define WINRT_Windows_Phone_Speech_Recognition_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Phone.Speech.Recognition.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::Phone::Speech::Recognition
{
}
#endif
