// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Windows_Phone_Media_Devices_1_H
#define WINRT_Windows_Phone_Media_Devices_1_H
#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/impl/Windows.Phone.Media.Devices.0.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::Windows::Phone::Media::Devices
{
    struct WINRT_IMPL_EMPTY_BASES IAudioRoutingManager :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAudioRoutingManager>
    {
        IAudioRoutingManager(std::nullptr_t = nullptr) noexcept {}
        IAudioRoutingManager(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IAudioRoutingManagerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAudioRoutingManagerStatics>
    {
        IAudioRoutingManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAudioRoutingManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
